### ISSUE TITLE
[Feature] Finalizar a implementação do login

### ISSUE THREAD

**Issue by sidneyouteiro** [sidneyouteiro/EducacaoPermanente#9]
## Descrição da Feature

* Onde será implementada, front ou back?
Back
* Qual o resultado esperado?
Proteger as rotas que necessitem do token JWT e que precisam do usuário logado 
* Prazo?
26/06

**Comment by RaphaelAN** [comment]
Esse issue não é uma repetição do issue 14?

**Comment by sidneyouteiro** [comment]
True, eu tinha editado pois no front já tá arrumado isso e nem me liguei que é basicamente a issue 14

> Esse issue não é uma repetição do issue 14?
